// react/src/App.js
import React from 'react';
import logo from './logo.svg';
import './App.css';
import '@vaadin/vaadin-tabs';
import '@vaadin/vaadin-accordion';

class App extends React.Component {
    constructor(props) {
        super(props);

        this.addTab = this.addTab.bind(this);
        this.tabChanged = this.tabChanged.bind(this);
        this.counter = 4;
        this.tabsWc = null;

        this.state = {
            selected: 1,
            tabs: [
                {name: 'Tab one'},
                {name: 'Tab two'},
                {name: 'Tab three'},
            ],
        };
    }

    componentDidMount() {
        this.tabsWc.addEventListener('selected-changed', this.tabChanged);
    }

    tabChanged(e) {
        e.preventDefault();

        this.setState({
            selected: e.detail.value
        });
    }

    addTab(e) {
        e.preventDefault();

        this.setState((state, props) => {
            return {
                tabs: state.tabs.concat([{name: `Tab ${this.counter++}`}])
            }
        });
    }

    render() {
        return (
            <div className="App">
                <div className="tabs-container">
                    <vaadin-accordion>

                        <vaadin-accordion-panel>
                            <div slot="summary">Tabs</div>

                            <button onClick={this.addTab}>Add tab</button>
                            <p>
                                Selected tab: {this.state.selected + 1}
                            </p>

                            <vaadin-tabs selected={this.state.selected} ref={(el) => this.tabsWc = el}>
                                {
                                    this.state.tabs.map(v =>
                                        <vaadin-tab key={v.name}>{v.name}</vaadin-tab>
                                    )
                                }
                            </vaadin-tabs>
                        </vaadin-accordion-panel>

                        <vaadin-accordion-panel>
                            <div slot="summary">Not tabs</div>

                            <header className="App-header">
                                <img src={logo} className="App-logo" alt="logo"/>
                                <p>
                                    Edit <code>src/App.js</code> and save to reload.
                                </p>
                                <a
                                    className="App-link"
                                    href="https://reactjs.org"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                >
                                    Learn React
                                </a>
                            </header>

                        </vaadin-accordion-panel>
                    </vaadin-accordion>

                </div>
            </div>
        );
    }
}

export default App;

// vuejs/src/App.vue
<template>
    <div id="app">

        <vaadin-accordion>

            <vaadin-accordion-panel>
                <div slot="summary">Tabs</div>

                <button v-on:click="addTab">Add tab</button>
                <p>
                    Selected tab: {{selected + 1}}
                </p>

                <vaadin-tabs v-bind:selected="selected" v-on:selected-changed="tabChanged">
                    <vaadin-tab v-bind:key="v.name" v-for="v in tabs">{{v.name}}</vaadin-tab>
                </vaadin-tabs>

            </vaadin-accordion-panel>

            <vaadin-accordion-panel>
                <div slot="summary">Vue starter</div>

                <img alt="Vue logo" src="./assets/logo.png">
                <HelloWorld msg="Welcome to Your Vue.js App"/>

            </vaadin-accordion-panel>
        </vaadin-accordion>




    </div>
</template>

<script>
    import HelloWorld from './components/HelloWorld.vue'

    import '@vaadin/vaadin-accordion';
    import '@vaadin/vaadin-tabs';

    export default {
        name: 'app',
        components: {
            HelloWorld
        },
        data: function () {
            return {
                selected: 1,
                tabs: [
                    {name: 'Tab one'},
                    {name: 'Tab two'},
                    {name: 'Tab three'},
                ],
            };
        },
        methods: {
            tabChanged: function (e) {
                this.selected = e.detail.value;
            },
            addTab(e) {
                e.preventDefault();

                this.tabs = this.tabs.concat([{name: `Tab ${this.tabs.length + 1}`}]);
            }
        }
    }
</script>

<style>
    #app {
        font-family: 'Avenir', Helvetica, Arial, sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        text-align: center;
        color: #2c3e50;
        margin-top: 60px;
        padding: 50px 20px;
    }
</style>
